apiVersion: v1
kind: Pod
metadata:
  labels:
    app: s3-browser
  name: s3-browser
  namespace: opsfleet
spec:
  serviceAccountName: test-service-account
  containers:
  - name: s3-browser
    image: amazon/aws-cli
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    name: s3-browser
  restartPolicy: Always